In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Perfilado y Diagnóstico de Calidad de Datos

## Dataset 1: Cobertura móvil por centro poblado, empresa operadora y tecnología

In [6]:
df_cobertura = pd.read_excel("C:/Users/Us/Documents/GitHub/Python/Proyecto Analisis de Datos/Datasets/Porcentaje de cobertura movil por centro poblado empresa operadora y tecnología_F.xlsx")

In [7]:
df_cobertura.head()

,Ubigeo,Departamento,Provincia,Distrito,CentroPoblado,Clasificacion,Latitud,Longitud,Bitel_3G_CG,Bitel_3G_CG+CAR,...,Entel_4G_CG,Entel_4G_CG+CAR,Entel_5G_CG,Entel_5G_CG+CAR,Telefonica_2G_CG,Telefonica_2G_CG+CAR,Telefonica_3G_CG,Telefonica_3G_CG+CAR,Telefonica_4G_CG,Telefonica_4G_CG+CAR
0,101010001,AMAZONAS,CHACHAPOYAS,CHACHAPOYAS,CHACHAPOYAS,URBANO,-6.22941,-77.87250,0.891988,0.998472,...,0.009713,0.975131,0,0.0,0.347482,0.969168,0.943582,0.982455,0.992093,1.000000
1,101010002,AMAZONAS,CHACHAPOYAS,CHACHAPOYAS,CACLIC,RURAL,-6.20244,-77.90147,0.000000,0.000000,...,0.000000,0.388043,0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,101010003,AMAZONAS,CHACHAPOYAS,CHACHAPOYAS,VITALIANO,RURAL,-6.20987,-77.87266,0.557475,1.000000,...,0.000000,0.857450,0,0.0,0.000000,0.921899,0.556374,0.637153,1.000000,1.000000
3,101010004,AMAZONAS,CHACHAPOYAS,CHACHAPOYAS,EL TAPIAL,RURAL,-6.20844,-77.86759,0.974030,1.000000,...,0.000000,0.483910,0,0.0,0.000000,0.986994,0.108838,0.316342,1.000000,1.000000
4,101010005,AMAZONAS,CHACHAPOYAS,CHACHAPOYAS,RONDON,RURAL,-6.22025,-77.82419,0.000000,0.000000,...,0.000000,0.036687,0,0.0,0.000000,0.359108,0.000000,0.000000,0.000000,0.426363

In [8]:
df_cobertura.info()

<class 'pandas.DataFrame'>
RangeIndex: 108115 entries, 0 to 108114
Data columns (total 36 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Ubigeo                108115 non-null  int64
 1   Departamento          108115 non-null  str
 2   Provincia             108115 non-null  str
 3   Distrito              108115 non-null  str
 4   CentroPoblado         108115 non-null  str
 5   Clasificacion         108115 non-null  str
 6   Latitud               108115 non-null  float64
 7   Longitud              108115 non-null  float64
 8   Bitel_3G_CG           108115 non-null  float64
 9   Bitel_3G_CG+CAR       108115 non-null  float64
 10  Bitel_4G_CG           108115 non-null  float64
 11  Bitel_4G_CG+CAR       108115 non-null  float64
 12  Bitel_5G_CG           108115 non-null  float64
 13  Bitel_5G_CG+CAR       108115 non-null  float64
 14  Claro_2G_CG           108115 non-null  float64
 15  Claro_2G_CG+CAR       108115 non-null  float64
 16  Claro_3G_CG           108115 non-null  float64
 17  Claro_3G_CG+CAR       108115 non-null  float64
 18  Claro_4G_CG           108115 non-null  float64
 19  Claro_4G_CG+CAR       108115 non-null  float64
 20  Claro_5G_CG           108115 non-null  float64
 21  Claro_5G_CG+CAR       108115 non-null  float64
 22  Entel_2G_CG           108115 non-null  int64
 23  Entel_2G_CG+CAR       108115 non-null  float64
 24  Entel_3G_CG           108115 non-null  int64
 25  Entel_3G_CG+CAR       108115 non-null  float64
 26  Entel_4G_CG           108115 non-null  float64
 27  Entel_4G_CG+CAR       108115 non-null  float64
 28  Entel_5G_CG           108115 non-null  int64
 29  Entel_5G_CG+CAR       108115 non-null  float64
 30  Telefonica_2G_CG      108115 non-null  float64
 31  Telefonica_2G_CG+CAR  108115 non-null  float64
 32  Telefonica_3G_CG      108115 non-null  float64
 33  Telefonica_3G_CG+CAR  108115 non-null  float64
 34  Telefonica_4G_CG      108115 non-null  float64
 35  Telefonica_4G_CG+CAR  108115 non-null  float64
dtypes: float64(27), int64(4), str(5)
memory usage: 29.7 MB

In [9]:
df_cobertura.shape

(108115, 36)

In [10]:
df_cobertura.dtypes

Ubigeo                    int64
Departamento                str
Provincia                   str
Distrito                    str
CentroPoblado               str
Clasificacion               str
Latitud                 float64
Longitud                float64
Bitel_3G_CG             float64
Bitel_3G_CG+CAR         float64
Bitel_4G_CG             float64
Bitel_4G_CG+CAR         float64
Bitel_5G_CG             float64
Bitel_5G_CG+CAR         float64
Claro_2G_CG             float64
Claro_2G_CG+CAR         float64
Claro_3G_CG             float64
Claro_3G_CG+CAR         float64
Claro_4G_CG             float64
Claro_4G_CG+CAR         float64
Claro_5G_CG             float64
Claro_5G_CG+CAR         float64
Entel_2G_CG               int64
Entel_2G_CG+CAR         float64
Entel_3G_CG               int64
Entel_3G_CG+CAR         float64
Entel_4G_CG             float64
Entel_4G_CG+CAR         float64
Entel_5G_CG               int64
Entel_5G_CG+CAR         float64
Telefonica_2G_CG        float64
Telefonica_2G_CG+CAR    float64
Telefonica_3G_CG        float64
Telefonica_3G_CG+CAR    float64
Telefonica_4G_CG        float64
Telefonica_4G_CG+CAR    float64
dtype: object

In [11]:
df_cobertura.isnull().sum()

Ubigeo                  0
Departamento            0
Provincia               0
Distrito                0
CentroPoblado           0
Clasificacion           0
Latitud                 0
Longitud                0
Bitel_3G_CG             0
Bitel_3G_CG+CAR         0
Bitel_4G_CG             0
Bitel_4G_CG+CAR         0
Bitel_5G_CG             0
Bitel_5G_CG+CAR         0
Claro_2G_CG             0
Claro_2G_CG+CAR         0
Claro_3G_CG             0
Claro_3G_CG+CAR         0
Claro_4G_CG             0
Claro_4G_CG+CAR         0
Claro_5G_CG             0
Claro_5G_CG+CAR         0
Entel_2G_CG             0
Entel_2G_CG+CAR         0
Entel_3G_CG             0
Entel_3G_CG+CAR         0
Entel_4G_CG             0
Entel_4G_CG+CAR         0
Entel_5G_CG             0
Entel_5G_CG+CAR         0
Telefonica_2G_CG        0
Telefonica_2G_CG+CAR    0
Telefonica_3G_CG        0
Telefonica_3G_CG+CAR    0
Telefonica_4G_CG        0
Telefonica_4G_CG+CAR    0
dtype: int64

In [12]:
(df_cobertura.isnull().sum() / len(df_cobertura)) * 100

Ubigeo                  0.0
Departamento            0.0
Provincia               0.0
Distrito                0.0
CentroPoblado           0.0
Clasificacion           0.0
Latitud                 0.0
Longitud                0.0
Bitel_3G_CG             0.0
Bitel_3G_CG+CAR         0.0
Bitel_4G_CG             0.0
Bitel_4G_CG+CAR         0.0
Bitel_5G_CG             0.0
Bitel_5G_CG+CAR         0.0
Claro_2G_CG             0.0
Claro_2G_CG+CAR         0.0
Claro_3G_CG             0.0
Claro_3G_CG+CAR         0.0
Claro_4G_CG             0.0
Claro_4G_CG+CAR         0.0
Claro_5G_CG             0.0
Claro_5G_CG+CAR         0.0
Entel_2G_CG             0.0
Entel_2G_CG+CAR         0.0
Entel_3G_CG             0.0
Entel_3G_CG+CAR         0.0
Entel_4G_CG             0.0
Entel_4G_CG+CAR         0.0
Entel_5G_CG             0.0
Entel_5G_CG+CAR         0.0
Telefonica_2G_CG        0.0
Telefonica_2G_CG+CAR    0.0
Telefonica_3G_CG        0.0
Telefonica_3G_CG+CAR    0.0
Telefonica_4G_CG        0.0
Telefonica_4G_CG+CAR    0.0
dtype: float64

In [13]:
df_cobertura.duplicated().sum()

np.int64(0)

In [14]:
df_cobertura.describe()

,Ubigeo,Latitud,Longitud,Bitel_3G_CG,Bitel_3G_CG+CAR,Bitel_4G_CG,Bitel_4G_CG+CAR,Bitel_5G_CG,Bitel_5G_CG+CAR,Claro_2G_CG,...,Entel_4G_CG,Entel_4G_CG+CAR,Entel_5G_CG,Entel_5G_CG+CAR,Telefonica_2G_CG,Telefonica_2G_CG+CAR,Telefonica_3G_CG,Telefonica_3G_CG+CAR,Telefonica_4G_CG,Telefonica_4G_CG+CAR
count,1.081150e+05,108115.000000,108115.000000,108115.000000,108115.000000,108115.000000,108115.000000,108115.000000,108115.000000,108115.000000,...,108115.000000,108115.000000,108115.0,108115.000000,108115.000000,108115.000000,108115.000000,108115.000000,108115.000000,108115.000000
mean,1.075746e+09,-11.352972,-74.914108,0.154873,0.273435,0.139933,0.315476,0.000364,0.002002,0.045426,...,0.004464,0.441831,0.0,0.003078,0.108550,0.442953,0.044632,0.108314,0.037999,0.410714
std,6.666826e+08,3.485571,2.926393,0.327682,0.419375,0.319038,0.445314,0.011716,0.038642,0.177104,...,0.037907,0.473065,0.0,0.050603,0.284515,0.459627,0.189587,0.290919,0.178445,0.460835
min,1.010100e+08,-18.335060,-81.305700,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.061102e+08,-14.186010,-77.209880,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,9.061001e+08,-12.146150,-75.261790,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.064879,0.0,0.000000,0.000000,0.203132,0.000000,0.000000,0.000000,0.023698
75%,1.601030e+09,-8.693695,-72.305940,0.000000,0.717844,0.000000,0.971685,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
max,2.504010e+09,-0.095670,-68.659020,1.000000,1.000000,1.000000,1.000000,0.996755,1.000000,1.000000,...,0.987363,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

## Categorías raras

No se encontraron categorías raras ni inconsistencias en las variables categóricas analizadas.

In [15]:
df_cobertura.columns

Index(['Ubigeo', 'Departamento', 'Provincia', 'Distrito', 'CentroPoblado',
       'Clasificacion', 'Latitud', 'Longitud', 'Bitel_3G_CG',
       'Bitel_3G_CG+CAR', 'Bitel_4G_CG', 'Bitel_4G_CG+CAR', 'Bitel_5G_CG',
       'Bitel_5G_CG+CAR', 'Claro_2G_CG', 'Claro_2G_CG+CAR', 'Claro_3G_CG',
       'Claro_3G_CG+CAR', 'Claro_4G_CG', 'Claro_4G_CG+CAR', 'Claro_5G_CG',
       'Claro_5G_CG+CAR', 'Entel_2G_CG', 'Entel_2G_CG+CAR', 'Entel_3G_CG',
       'Entel_3G_CG+CAR', 'Entel_4G_CG', 'Entel_4G_CG+CAR', 'Entel_5G_CG',
       'Entel_5G_CG+CAR', 'Telefonica_2G_CG', 'Telefonica_2G_CG+CAR',
       'Telefonica_3G_CG', 'Telefonica_3G_CG+CAR', 'Telefonica_4G_CG',
       'Telefonica_4G_CG+CAR'],
      dtype='str')

In [16]:
df_cobertura["Bitel_3G_CG"].describe()

count    108115.000000
mean          0.154873
std           0.327682
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Bitel_3G_CG, dtype: float64

In [17]:
df_cobertura["Bitel_3G_CG+CAR"].describe()

count    108115.000000
mean          0.273435
std           0.419375
min           0.000000
25%           0.000000
50%           0.000000
75%           0.717844
max           1.000000
Name: Bitel_3G_CG+CAR, dtype: float64

In [18]:
df_cobertura["Bitel_4G_CG"].describe()

count    108115.000000
mean          0.139933
std           0.319038
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Bitel_4G_CG, dtype: float64

In [19]:
df_cobertura["Bitel_4G_CG+CAR"].describe()

count    108115.000000
mean          0.315476
std           0.445314
min           0.000000
25%           0.000000
50%           0.000000
75%           0.971685
max           1.000000
Name: Bitel_4G_CG+CAR, dtype: float64

In [20]:
df_cobertura["Bitel_5G_CG"].describe()

count    108115.000000
mean          0.000364
std           0.011716
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           0.996755
Name: Bitel_5G_CG, dtype: float64

In [21]:
df_cobertura["Bitel_5G_CG+CAR"].describe()

count    108115.000000
mean          0.002002
std           0.038642
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Bitel_5G_CG+CAR, dtype: float64

In [22]:
df_cobertura["Claro_2G_CG"].describe()

count    108115.000000
mean          0.045426
std           0.177104
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Claro_2G_CG, dtype: float64

In [23]:
df_cobertura["Claro_2G_CG+CAR"].describe()

count    108115.000000
mean          0.359181
std           0.453759
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: Claro_2G_CG+CAR, dtype: float64

In [24]:
df_cobertura["Claro_3G_CG"].describe()

count    108115.000000
mean          0.011846
std           0.079580
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Claro_3G_CG, dtype: float64

In [25]:
df_cobertura["Claro_3G_CG+CAR"].describe()

count    108115.000000
mean          0.316224
std           0.434107
min           0.000000
25%           0.000000
50%           0.000000
75%           0.900953
max           1.000000
Name: Claro_3G_CG+CAR, dtype: float64

In [26]:
df_cobertura["Claro_4G_CG"].describe()

count    108115.000000
mean          0.007125
std           0.057512
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Claro_4G_CG, dtype: float64

In [27]:
df_cobertura["Claro_4G_CG+CAR"].describe()

count    108115.000000
mean          0.218627
std           0.373437
min           0.000000
25%           0.000000
50%           0.000000
75%           0.300414
max           1.000000
Name: Claro_4G_CG+CAR, dtype: float64

In [28]:
df_cobertura["Claro_5G_CG"].describe()

count    108115.000000
mean          0.000127
std           0.007745
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Claro_5G_CG, dtype: float64

In [29]:
df_cobertura["Claro_5G_CG+CAR"].describe()

count    108115.000000
mean          0.001142
std           0.029131
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Claro_5G_CG+CAR, dtype: float64

In [30]:
df_cobertura["Entel_2G_CG"].describe()

count    108115.0
mean          0.0
std           0.0
min           0.0
25%           0.0
50%           0.0
75%           0.0
max           0.0
Name: Entel_2G_CG, dtype: float64

In [31]:
df_cobertura["Entel_2G_CG+CAR"].describe()

count    108115.000000
mean          0.198746
std           0.384990
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Entel_2G_CG+CAR, dtype: float64

In [32]:
df_cobertura["Entel_3G_CG"].describe()

count    108115.0
mean          0.0
std           0.0
min           0.0
25%           0.0
50%           0.0
75%           0.0
max           0.0
Name: Entel_3G_CG, dtype: float64

In [33]:
df_cobertura["Entel_3G_CG+CAR"].describe()

count    108115.000000
mean          0.315604
std           0.442934
min           0.000000
25%           0.000000
50%           0.000000
75%           0.954033
max           1.000000
Name: Entel_3G_CG+CAR, dtype: float64

In [34]:
df_cobertura["Entel_4G_CG"].describe()

count    108115.000000
mean          0.004464
std           0.037907
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           0.987363
Name: Entel_4G_CG, dtype: float64

In [35]:
df_cobertura["Entel_4G_CG+CAR"].describe()

count    108115.000000
mean          0.441831
std           0.473065
min           0.000000
25%           0.000000
50%           0.064879
75%           1.000000
max           1.000000
Name: Entel_4G_CG+CAR, dtype: float64

In [36]:
df_cobertura["Entel_5G_CG"].describe()

count    108115.0
mean          0.0
std           0.0
min           0.0
25%           0.0
50%           0.0
75%           0.0
max           0.0
Name: Entel_5G_CG, dtype: float64

In [37]:
df_cobertura["Entel_5G_CG+CAR"].describe()

count    108115.000000
mean          0.003078
std           0.050603
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Entel_5G_CG+CAR, dtype: float64

In [38]:
df_cobertura["Telefonica_2G_CG"].describe()

count    108115.000000
mean          0.108550
std           0.284515
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Telefonica_2G_CG, dtype: float64

In [39]:
df_cobertura["Telefonica_2G_CG+CAR"].describe()

count    108115.000000
mean          0.442953
std           0.459627
min           0.000000
25%           0.000000
50%           0.203132
75%           1.000000
max           1.000000
Name: Telefonica_2G_CG+CAR, dtype: float64

In [40]:
df_cobertura["Telefonica_3G_CG"].describe()

count    108115.000000
mean          0.044632
std           0.189587
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Telefonica_3G_CG, dtype: float64

In [41]:
df_cobertura["Telefonica_3G_CG+CAR"].describe()

count    108115.000000
mean          0.108314
std           0.290919
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Telefonica_3G_CG+CAR, dtype: float64

In [42]:
df_cobertura["Telefonica_4G_CG"].describe()

count    108115.000000
mean          0.037999
std           0.178445
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: Telefonica_4G_CG, dtype: float64

In [43]:
df_cobertura["Telefonica_4G_CG+CAR"].describe()

count    108115.000000
mean          0.410714
std           0.460835
min           0.000000
25%           0.000000
50%           0.023698
75%           1.000000
max           1.000000
Name: Telefonica_4G_CG+CAR, dtype: float64

## Rangos inconsistentes

Se revisaron las variables numéricas del dataset mediante estadísticas descriptivas.
No se identificaron valores fuera de los rangos esperados ni inconsistencias numéricas significativas.

In [45]:
df_cobertura.columns

Index(['Ubigeo', 'Departamento', 'Provincia', 'Distrito', 'CentroPoblado',
       'Clasificacion', 'Latitud', 'Longitud', 'Bitel_3G_CG',
       'Bitel_3G_CG+CAR', 'Bitel_4G_CG', 'Bitel_4G_CG+CAR', 'Bitel_5G_CG',
       'Bitel_5G_CG+CAR', 'Claro_2G_CG', 'Claro_2G_CG+CAR', 'Claro_3G_CG',
       'Claro_3G_CG+CAR', 'Claro_4G_CG', 'Claro_4G_CG+CAR', 'Claro_5G_CG',
       'Claro_5G_CG+CAR', 'Entel_2G_CG', 'Entel_2G_CG+CAR', 'Entel_3G_CG',
       'Entel_3G_CG+CAR', 'Entel_4G_CG', 'Entel_4G_CG+CAR', 'Entel_5G_CG',
       'Entel_5G_CG+CAR', 'Telefonica_2G_CG', 'Telefonica_2G_CG+CAR',
       'Telefonica_3G_CG', 'Telefonica_3G_CG+CAR', 'Telefonica_4G_CG',
       'Telefonica_4G_CG+CAR'],
      dtype='str')

In [46]:
df_cobertura["Latitud"].describe()

count    108115.000000
mean        -11.352972
std           3.485571
min         -18.335060
25%         -14.186010
50%         -12.146150
75%          -8.693695
max          -0.095670
Name: Latitud, dtype: float64

In [47]:
df_cobertura["Longitud"].describe()

count    108115.000000
mean        -74.914108
std           2.926393
min         -81.305700
25%         -77.209880
50%         -75.261790
75%         -72.305940
max         -68.659020
Name: Longitud, dtype: float64

## Rangos inconsistentes

Se revisaron las variables numéricas y geográficas del dataset mediante estadísticas descriptivas.

Las coordenadas geográficas presentan valores coherentes con el territorio peruano y las variables de cobertura móvil muestran rangos válidos entre 0 y 1.

No se identificaron inconsistencias significativas en los rangos analizados.

In [48]:
Q1 = df_cobertura["Bitel_3G_CG"].quantile(0.25)
Q3 = df_cobertura["Bitel_3G_CG"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_cobertura[
    (df_cobertura["Bitel_3G_CG"] < limite_inferior) |
    (df_cobertura["Bitel_3G_CG"] > limite_superior)
]

len(outliers)

25844

In [50]:
Q1 = df_cobertura["Bitel_3G_CG+CAR"].quantile(0.25)
Q3 = df_cobertura["Bitel_3G_CG+CAR"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_cobertura[
    (df_cobertura["Bitel_3G_CG+CAR"] < limite_inferior) |
    (df_cobertura["Bitel_3G_CG+CAR"] > limite_superior)
]

len(outliers)

0

In [51]:
Q1 = df_cobertura["Bitel_4G_CG"].quantile(0.25)
Q3 = df_cobertura["Bitel_4G_CG"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_cobertura[
    (df_cobertura["Bitel_4G_CG"] < limite_inferior) |
    (df_cobertura["Bitel_4G_CG"] > limite_superior)
]

len(outliers)

22360

In [52]:
Q1 = df_cobertura["Bitel_4G_CG+CAR"].quantile(0.25)
Q3 = df_cobertura["Bitel_4G_CG+CAR"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_cobertura[
    (df_cobertura["Bitel_4G_CG+CAR"] < limite_inferior) |
    (df_cobertura["Bitel_4G_CG+CAR"] > limite_superior)
]

len(outliers)

0

In [53]:
Q1 = df_cobertura["Bitel_5G_CG"].quantile(0.25)
Q3 = df_cobertura["Bitel_5G_CG"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_cobertura[
    (df_cobertura["Bitel_5G_CG"] < limite_inferior) |
    (df_cobertura["Bitel_5G_CG"] > limite_superior)
]

len(outliers)

196

In [54]:
Q1 = df_cobertura["Bitel_5G_CG+CAR"].quantile(0.25)
Q3 = df_cobertura["Bitel_5G_CG+CAR"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_cobertura[
    (df_cobertura["Bitel_5G_CG+CAR"] < limite_inferior) |
    (df_cobertura["Bitel_5G_CG+CAR"] > limite_superior)
]

len(outliers)

452

In [55]:
Q1 = df_cobertura["Claro_2G_CG"].quantile(0.25)
Q3 = df_cobertura["Claro_2G_CG"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_cobertura[
    (df_cobertura["Claro_2G_CG"] < limite_inferior) |
    (df_cobertura["Claro_2G_CG"] > limite_superior)
]

len(outliers)

10440

In [56]:
Q1 = df_cobertura["Claro_2G_CG+CAR"].quantile(0.25)
Q3 = df_cobertura["Claro_2G_CG+CAR"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_cobertura[
    (df_cobertura["Claro_2G_CG+CAR"] < limite_inferior) |
    (df_cobertura["Claro_2G_CG+CAR"] > limite_superior)
]

len(outliers)

0

In [57]:
Q1 = df_cobertura["Claro_3G_CG"].quantile(0.25)
Q3 = df_cobertura["Claro_3G_CG"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_cobertura[
    (df_cobertura["Claro_3G_CG"] < limite_inferior) |
    (df_cobertura["Claro_3G_CG"] > limite_superior)
]

len(outliers)

4166

In [58]:
Q1 = df_cobertura["Claro_3G_CG+CAR"].quantile(0.25)
Q3 = df_cobertura["Claro_3G_CG+CAR"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_cobertura[
    (df_cobertura["Claro_3G_CG+CAR"] < limite_inferior) |
    (df_cobertura["Claro_3G_CG+CAR"] > limite_superior)
]

len(outliers)

0

In [59]:
Q1 = df_cobertura["Claro_4G_CG"].quantile(0.25)
Q3 = df_cobertura["Claro_4G_CG"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_cobertura[
    (df_cobertura["Claro_4G_CG"] < limite_inferior) |
    (df_cobertura["Claro_4G_CG"] > limite_superior)
]

len(outliers)

3050

In [60]:
Q1 = df_cobertura["Claro_4G_CG+CAR"].quantile(0.25)
Q3 = df_cobertura["Claro_4G_CG+CAR"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_cobertura[
    (df_cobertura["Claro_4G_CG+CAR"] < limite_inferior) |
    (df_cobertura["Claro_4G_CG+CAR"] > limite_superior)
]

len(outliers)

19277

In [61]:
Q1 = df_cobertura["Claro_5G_CG"].quantile(0.25)
Q3 = df_cobertura["Claro_5G_CG"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_cobertura[
    (df_cobertura["Claro_5G_CG"] < limite_inferior) |
    (df_cobertura["Claro_5G_CG"] > limite_superior)
]

len(outliers)

91

In [62]:
Q1 = df_cobertura["Claro_5G_CG+CAR"].quantile(0.25)
Q3 = df_cobertura["Claro_5G_CG+CAR"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_cobertura[
    (df_cobertura["Claro_5G_CG+CAR"] < limite_inferior) |
    (df_cobertura["Claro_5G_CG+CAR"] > limite_superior)
]

len(outliers)

258

In [63]:
Q1 = df_cobertura["Entel_2G_CG"].quantile(0.25)
Q3 = df_cobertura["Entel_2G_CG"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_cobertura[
    (df_cobertura["Entel_2G_CG"] < limite_inferior) |
    (df_cobertura["Entel_2G_CG"] > limite_superior)
]

len(outliers)

0

In [64]:
Q1 = df_cobertura["Entel_2G_CG+CAR"].quantile(0.25)
Q3 = df_cobertura["Entel_2G_CG+CAR"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_cobertura[
    (df_cobertura["Entel_2G_CG+CAR"] < limite_inferior) |
    (df_cobertura["Entel_2G_CG+CAR"] > limite_superior)
]

len(outliers)

25439

In [65]:
Q1 = df_cobertura["Entel_3G_CG+CAR"].quantile(0.25)
Q3 = df_cobertura["Entel_3G_CG+CAR"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_cobertura[
    (df_cobertura["Entel_3G_CG+CAR"] < limite_inferior) |
    (df_cobertura["Entel_3G_CG+CAR"] > limite_superior)
]

len(outliers)

0

In [66]:
Q1 = df_cobertura["Entel_4G_CG"].quantile(0.25)
Q3 = df_cobertura["Entel_4G_CG"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_cobertura[
    (df_cobertura["Entel_4G_CG"] < limite_inferior) |
    (df_cobertura["Entel_4G_CG"] > limite_superior)
]

len(outliers)

2916

In [67]:
Q1 = df_cobertura["Entel_4G_CG+CAR"].quantile(0.25)
Q3 = df_cobertura["Entel_4G_CG+CAR"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_cobertura[
    (df_cobertura["Entel_4G_CG+CAR"] < limite_inferior) |
    (df_cobertura["Entel_4G_CG+CAR"] > limite_superior)
]

len(outliers)

0

In [ ]:
Q1 = df_cobertura["Entel_5G_CG"].quantile(0.25)
Q3 = df_cobertura["Entel_5G_CG"].quantile(0.75)

IQR = Q3 - Q1

limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df_cobertura[
    (df_cobertura["Entel_5G_CG"] < limite_inferior) |
    (df_cobertura["Entel_G_CG"] > limite_superior)
]

len(outliers)